More DevWorkstationUpdate work
I needed to manually reset the node version for yarn. Once past that the install part of the script appears to exit clean.

However, during the build it existed with
@container-images/mds-geography-author: ../../node_modules/@mds-core/mds-types/dist/index.d.ts(2,72): error TS2306: File '/Users/sarob/code/lacuna-tech-mds-core/node_modules/@mds-core/mds-types/dist/scopes.d.ts' is not a module.

I will include the updated config files this time.